image: gitpod/workspace-dotnet-lts

tasks:
  - name: Gitpod Init
    command: |
      gp preview http://localhost:5000/swagger/index.html
      exit
  - name: HeartRateZoneService
    openMode: tab-before
    init: |
      mkdir exercises/HeartRateZoneService
    command: |
      cd exercises/HeartRateZoneService
  - name: ClientGateway
    openMode: tab-before
    init: |
      mkdir exercises/ClientGateway
    command: |
      cd exercises/ClientGateway
  - name: exercises
    openMode: tab-before
    command: |
      cd exercises

ports:
  - port: 5000
    onOpen: ignore

workspaceLocation: /workspace/learn-apache-kafka-for-dotnet-developers-exercises